name: dart_application_9
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.1.0

# Add regular dependencies here.
dependencies:
  source_gen: ^1.4.0
  source_gen_example:
    path: ./example
  # path: ^1.8.0

dev_dependencies:
  build_runner: ^2.4.6
  lints: ^2.0.0
  test: ^1.21.0
